name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTH_BACKEND: pro
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Pylint
        run: |
          uv run pylint --ignore-paths=.venv --fail-on=W,E,F --exit-zero ./

      - name: Run Flake8
        run: |
          uv run flake8 .

      - name: Run mypy
        run: |
          # run mypy but exit with 0 even if there are errors
          uv run mypy . || true

      - name: Run Black
        run: |
          uv run black --check .

      - name: Run unit tests
        run: uv run pytest ./tests/
